apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresdb-pvc
  namespace: training
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
       storage: 2Gi
