apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dbtraffic
  namespace: training
spec:
  podSelector:
    matchLabels:
      name: pgmodule
  ingress:
    - from:
        - podSelector:
            matchLabels:
              name: servermodule
        - podSelector:
            matchLabels:
              name: workermodule
        - podSelector:
            matchLabels:
              name: clientmodule
      ports:
        -  port: 5432