apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: client-ingress
  namespace: training
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: client
              servicePort: 3000

          - path: /server
            backend:
              serviceName: api
              servicePort: 5000
